/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users/{id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changeRole"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["changeActive"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/scm-connections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put: operations["update_1"];
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ldap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_1"];
        put: operations["update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/impact-rules/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["updateRule"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/entry-point-annotations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["update_3"];
        post?: never;
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/artifact-repositories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_2"];
        put: operations["update_4"];
        post?: never;
        delete: operations["delete_2"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/index/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/index/runs/{runId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/impact": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["analyze"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/impact/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["export"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/scm-connections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_2"];
        put?: never;
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/scm-connections/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ldap/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/entry-point-annotations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["annotations"];
        put?: never;
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/artifact-repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_3"];
        put?: never;
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/artifact-repositories/{id}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["test_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/index.html": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ui-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["uiConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_3"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/{id}/usages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["usages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/{id}/usages/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/symbols/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_4"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["repositoryRuns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["graph"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}/graph/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/repositories/{id}/graph/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["export_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/index/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["csrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_5"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/ldap/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchDirectory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/impact-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["rules"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_6"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RoleChange: {
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        AppUser: {
            /** Format: int64 */
            id?: number;
            username?: string;
            /** @enum {string} */
            source?: "LOCAL" | "LDAP";
            displayName?: string;
            email?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
            roleGrantedBy?: string;
            /** Format: date-time */
            roleGrantedAt?: string;
            /** Format: date-time */
            lastLoginAt?: string;
            active?: boolean;
        };
        ActiveChange: {
            active?: boolean;
        };
        ValueChange: {
            value?: string;
        };
        Setting: {
            key?: string;
            value?: string;
            /** @enum {string} */
            type?: "INT" | "STRING" | "BOOL" | "CRON" | "LIST" | "DURATION";
            description?: string;
            /** Format: int64 */
            minValue?: number;
            /** Format: int64 */
            maxValue?: number;
            updatedBy?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ScmConnectionUpdate: {
            name?: string;
            /** @enum {string} */
            type?: "BITBUCKET_DC" | "GITHUB" | "GIT";
            baseUrl?: string;
            username?: string;
            secret?: string;
            includeProjects?: string[];
            excludeRepos?: string[];
            repositoryUrls?: string[];
            includeOwnRepositories?: boolean;
            enabled?: boolean;
        };
        ScmConnectionView: {
            /** Format: int64 */
            id?: number;
            name?: string;
            /** @enum {string} */
            type?: "BITBUCKET_DC" | "GITHUB" | "GIT";
            baseUrl?: string;
            username?: string;
            secretSet?: boolean;
            includeProjects?: string[];
            excludeRepos?: string[];
            repositoryUrls?: string[];
            includeOwnRepositories?: boolean;
            enabled?: boolean;
            lastTestStatus?: string;
            /** Format: date-time */
            lastTestAt?: string;
            lastSyncStatus?: string;
            /** Format: date-time */
            lastSyncAt?: string;
            lastSyncError?: string;
            /** Format: int32 */
            repositoryCount?: number;
        };
        LdapConfigUpdate: {
            enabled?: boolean;
            url?: string;
            baseDn?: string;
            userSearchBase?: string;
            userSearchFilter?: string;
            userQueryFilter?: string;
            usernameAttr?: string;
            displayNameAttr?: string;
            emailAttr?: string;
            bindDn?: string;
            bindPassword?: string;
        };
        LdapConfigView: {
            enabled?: boolean;
            url?: string;
            baseDn?: string;
            userSearchBase?: string;
            userSearchFilter?: string;
            userQueryFilter?: string;
            usernameAttr?: string;
            displayNameAttr?: string;
            emailAttr?: string;
            bindDn?: string;
            bindPasswordSet?: boolean;
            updatedBy?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        RuleChange: {
            propagates?: boolean;
            shownAtLevel1?: boolean;
        };
        ImpactRule: {
            /** @enum {string} */
            kind?: "CALL" | "INSTANTIATION" | "METHOD_REF" | "TYPE_REF" | "EXTENDS" | "IMPLEMENTS" | "OVERRIDES" | "FIELD_READ" | "FIELD_WRITE" | "ANNOTATION";
            propagates?: boolean;
            shownAtLevel1?: boolean;
        };
        AnnotationChange: {
            annotationFqn?: string;
            label?: string;
            enabled?: boolean;
        };
        EntryPointAnnotation: {
            /** Format: int64 */
            id?: number;
            annotationFqn?: string;
            label?: string;
            enabled?: boolean;
        };
        ArtifactRepositoryUpdate: {
            name?: string;
            url?: string;
            username?: string;
            secret?: string;
            mirrorOf?: string;
            /** Format: int32 */
            sortOrder?: number;
            enabled?: boolean;
        };
        ArtifactRepositoryView: {
            /** Format: int64 */
            id?: number;
            name?: string;
            url?: string;
            username?: string;
            secretSet?: boolean;
            mirrorOf?: string;
            /** Format: int32 */
            sortOrder?: number;
            enabled?: boolean;
            lastTestStatus?: string;
            /** Format: date-time */
            lastTestAt?: string;
        };
        StartRequest: {
            /** @enum {string} */
            scope?: "ALL" | "CONNECTION" | "REPOSITORY";
            /** Format: int64 */
            id?: number;
            force?: boolean;
        };
        StartedRun: {
            /** Format: int64 */
            runId?: number;
        };
        ImpactRequest: {
            symbolIds?: number[];
            /** @enum {string} */
            changeType?: "SIGNATURE" | "BEHAVIOR";
            /** Format: int32 */
            depth?: number;
            confidences?: ("EXACT" | "RECOVERED" | "NAME_ONLY")[];
            includeDispatch?: boolean;
        };
        EntryPoint: {
            /** Format: int64 */
            symbolId?: number;
            key?: string;
            display?: string;
            repository?: components["schemas"]["RepositoryRef"];
            modulePath?: string;
            label?: string;
            annotation?: string;
            http?: boolean;
            httpMethod?: string;
            httpPath?: string;
        };
        ImpactEdge: {
            /** Format: int64 */
            fromSymbolId?: number;
            /** Format: int64 */
            toSymbolId?: number;
            /** @enum {string} */
            kind?: "CALL" | "INSTANTIATION" | "METHOD_REF" | "TYPE_REF" | "EXTENDS" | "IMPLEMENTS" | "OVERRIDES" | "FIELD_READ" | "FIELD_WRITE" | "ANNOTATION";
            /** @enum {string} */
            confidence?: "EXACT" | "RECOVERED" | "NAME_ONLY";
            /** Format: int32 */
            level?: number;
            viaDispatch?: boolean;
            /** Format: int64 */
            moduleId?: number;
            repository?: components["schemas"]["RepositoryRef"];
            modulePath?: string;
            filePath?: string;
            /** Format: int32 */
            line?: number;
            /** Format: int32 */
            column?: number;
            snippet?: string;
        };
        ImpactNode: {
            /** Format: int64 */
            symbolId?: number;
            key?: string;
            /** @enum {string} */
            kind?: "CLASS" | "INTERFACE" | "ENUM" | "RECORD" | "ANNOTATION_TYPE" | "METHOD" | "CONSTRUCTOR" | "FIELD";
            display?: string;
            /** Format: int32 */
            level?: number;
            /** @enum {string} */
            role?: "SEED" | "AFFECTED" | "DISPATCH" | "TWIN";
            /** @enum {string} */
            confidence?: "EXACT" | "RECOVERED" | "NAME_ONLY";
            nameOnly?: boolean;
        };
        ImpactResult: {
            summary?: components["schemas"]["ImpactSummary"];
            nodes?: components["schemas"]["ImpactNode"][];
            edges?: components["schemas"]["ImpactEdge"][];
            entryPoints?: components["schemas"]["EntryPoint"][];
            staleness?: components["schemas"]["RepoState"][];
            versionWarnings?: components["schemas"]["VersionWarning"][];
            truncated?: boolean;
        };
        ImpactSummary: {
            /** Format: int32 */
            repositories?: number;
            /** Format: int32 */
            modules?: number;
            /** Format: int32 */
            classes?: number;
            /** Format: int32 */
            methods?: number;
            /** Format: int32 */
            usages?: number;
            usagesByLevel?: {
                [key: string]: number;
            };
            usagesByConfidence?: {
                [key: string]: number;
            };
            nodesByConfidence?: {
                [key: string]: number;
            };
            partialClasspathRepositories?: components["schemas"]["RepositoryRef"][];
        };
        RepoState: {
            /** Format: int64 */
            moduleId?: number;
            /** Format: int64 */
            repositoryId?: number;
            projectKey?: string;
            repository?: string;
            modulePath?: string;
            classpathMode?: string;
            lastIndexedCommit?: string;
            /** Format: date-time */
            lastIndexedAt?: string;
        };
        RepositoryRef: {
            /** Format: int64 */
            id?: number;
            projectKey?: string;
            slug?: string;
        };
        VersionWarning: {
            repository?: components["schemas"]["RepositoryRef"];
            modulePath?: string;
            dependency?: string;
            usedVersion?: string;
            declaredVersion?: string;
        };
        Credentials: {
            username?: string;
            password?: string;
        };
        Me: {
            username: string;
            displayName?: string;
            email?: string;
            /** @enum {string} */
            role: "ADMIN" | "USER";
            /** @enum {string} */
            source?: "LOCAL" | "LDAP";
            mustChangePassword: boolean;
        };
        PasswordChange: {
            currentPassword?: string;
            newPassword?: string;
        };
        Registration: {
            username?: string;
            /** @enum {string} */
            role?: "ADMIN" | "USER";
        };
        UiConfig: {
            /** Format: int32 */
            pageDefaultSize: number;
            /** Format: int32 */
            pageMaxSize: number;
            /** Format: int32 */
            graphMaxNodes: number;
            /** Format: int32 */
            impactDefaultDepth: number;
            /** Format: int32 */
            impactMaxDepth: number;
            /** Format: int64 */
            pollIntervalMillis: number;
        };
        DeclarationView: {
            repository?: components["schemas"]["RepositoryRef"];
            modulePath?: string;
            filePath?: string;
            /** Format: int32 */
            line?: number;
        };
        SymbolDetail: {
            symbol?: components["schemas"]["SymbolRef"];
            /** @enum {string} */
            origin?: "SOURCE" | "BINARY";
            nameOnly?: boolean;
            parent?: components["schemas"]["SymbolRef"];
            declarations?: components["schemas"]["DeclarationView"][];
            members?: components["schemas"]["SymbolRef"][];
            overrides?: components["schemas"]["SymbolRef"][];
            overriddenBy?: components["schemas"]["SymbolRef"][];
            supertypes?: components["schemas"]["SymbolRef"][];
            subtypes?: components["schemas"]["SymbolRef"][];
        };
        SymbolRef: {
            /** Format: int64 */
            id?: number;
            key?: string;
            /** @enum {string} */
            kind?: "CLASS" | "INTERFACE" | "ENUM" | "RECORD" | "ANNOTATION_TYPE" | "METHOD" | "CONSTRUCTOR" | "FIELD";
            display?: string;
        };
        PageUsageView: {
            items?: components["schemas"]["UsageView"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        UsageView: {
            /** Format: int64 */
            id?: number;
            from?: components["schemas"]["SymbolRef"];
            /** @enum {string} */
            kind?: "CALL" | "INSTANTIATION" | "METHOD_REF" | "TYPE_REF" | "EXTENDS" | "IMPLEMENTS" | "OVERRIDES" | "FIELD_READ" | "FIELD_WRITE" | "ANNOTATION";
            /** @enum {string} */
            confidence?: "EXACT" | "RECOVERED" | "NAME_ONLY";
            repository?: components["schemas"]["RepositoryRef"];
            modulePath?: string;
            filePath?: string;
            /** Format: int32 */
            line?: number;
            /** Format: int32 */
            column?: number;
            snippet?: string;
        };
        ClassUsage: {
            classFqn?: string;
            /** Format: int64 */
            usages?: number;
        };
        ModuleUsage: {
            modulePath?: string;
            /** Format: int64 */
            usages?: number;
            classes?: components["schemas"]["ClassUsage"][];
        };
        RepositoryUsage: {
            repository?: components["schemas"]["RepositoryRef"];
            /** Format: int64 */
            usages?: number;
            modules?: components["schemas"]["ModuleUsage"][];
        };
        UsageSummary: {
            /** Format: int64 */
            usages?: number;
            /** Format: int32 */
            repositories?: number;
            byRepository?: components["schemas"]["RepositoryUsage"][];
        };
        PageSymbolHit: {
            items?: components["schemas"]["SymbolHit"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        SymbolHit: {
            /** Format: int64 */
            id?: number;
            key?: string;
            /** @enum {string} */
            kind?: "CLASS" | "INTERFACE" | "ENUM" | "RECORD" | "ANNOTATION_TYPE" | "METHOD" | "CONSTRUCTOR" | "FIELD";
            display?: string;
            /** @enum {string} */
            origin?: "SOURCE" | "BINARY";
            nameOnly?: boolean;
            /** Format: int64 */
            usageCount?: number;
            /** Format: int32 */
            repositoryCount?: number;
        };
        PageRepositorySummary: {
            items?: components["schemas"]["RepositorySummary"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        RepositorySummary: {
            /** Format: int64 */
            id?: number;
            projectKey?: string;
            slug?: string;
            defaultBranch?: string;
            lastIndexedCommit?: string;
            /** Format: date-time */
            lastIndexedAt?: string;
            lastStatus?: string;
            active?: boolean;
            /** Format: int32 */
            moduleCount?: number;
        };
        ModuleView: {
            /** Format: int64 */
            id?: number;
            path?: string;
            groupId?: string;
            artifactId?: string;
            version?: string;
            classpathMode?: string;
        };
        RepositoryDetail: {
            repository?: components["schemas"]["RepositorySummary"];
            modules?: components["schemas"]["ModuleView"][];
        };
        IndexRunRepoView: {
            /** Format: int64 */
            runId?: number;
            repository?: components["schemas"]["RepositoryRef"];
            commit?: string;
            status?: string;
            classpathMode?: string;
            error?: string;
            /** Format: int32 */
            symbolCount?: number;
            /** Format: int32 */
            usageCount?: number;
            /** Format: int32 */
            warningCount?: number;
            /** Format: int64 */
            durationMs?: number;
            /** Format: date-time */
            finishedAt?: string;
            artifactInstall?: string;
            artifactInstallError?: string;
        };
        PageIndexRunRepoView: {
            items?: components["schemas"]["IndexRunRepoView"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        ClassMetrics: {
            /** Format: int32 */
            inDegree?: number;
            /** Format: int32 */
            outDegree?: number;
            /** Format: int32 */
            dependents?: number;
            entryPoint?: boolean;
            /** Format: int32 */
            communityId?: number;
            communityLabel?: string;
        };
        GraphEdge: {
            from?: string;
            to?: string;
            /** Format: int64 */
            weight?: number;
            kinds?: {
                [key: string]: number;
            };
        };
        GraphNode: {
            id?: string;
            label?: string;
            /** @enum {string} */
            type?: "MODULE" | "PACKAGE" | "CLASS" | "METHOD" | "CONSTRUCTOR" | "FIELD" | "EXTERNAL_REPOSITORY" | "EXTERNAL_LIBRARY";
            /** Format: int32 */
            size?: number;
            metrics?: components["schemas"]["ClassMetrics"];
        };
        RepoGraph: {
            /** Format: int64 */
            repositoryId?: number;
            /** @enum {string} */
            requestedLevel?: "MODULE" | "PACKAGE" | "CLASS" | "METHOD";
            /** @enum {string} */
            level?: "MODULE" | "PACKAGE" | "CLASS" | "METHOD";
            focus?: string;
            truncated?: boolean;
            suggestion?: string;
            nodes?: components["schemas"]["GraphNode"][];
            edges?: components["schemas"]["GraphEdge"][];
        };
        CommunitySummary: {
            /** Format: int32 */
            id?: number;
            label?: string;
            /** Format: int32 */
            size?: number;
        };
        CriticalClass: {
            /** Format: int64 */
            symbolId?: number;
            fqn?: string;
            /** Format: int32 */
            inDegree?: number;
            /** Format: int32 */
            outDegree?: number;
            /** Format: int32 */
            dependents?: number;
            entryPoint?: boolean;
        };
        PackageCycle: {
            /** Format: int32 */
            id?: number;
            packages?: string[];
        };
        RepoGraphReport: {
            /** Format: int64 */
            repositoryId?: number;
            indexedCommit?: string;
            analyzedCommit?: string;
            /** Format: date-time */
            analyzedAt?: string;
            stale?: boolean;
            /** Format: int32 */
            moduleCount?: number;
            /** Format: int32 */
            packageCount?: number;
            /** Format: int32 */
            classCount?: number;
            /** Format: int64 */
            dependencyCount?: number;
            /** Format: int32 */
            communityCount?: number;
            criticalClasses?: components["schemas"]["CriticalClass"][];
            communities?: components["schemas"]["CommunitySummary"][];
            cycles?: components["schemas"]["PackageCycle"][];
            /** Format: int32 */
            entryPointCount?: number;
            entryPointClasses?: string[];
        };
        IndexRunSummary: {
            /** Format: int64 */
            id?: number;
            trigger?: string;
            scope?: string;
            /** Format: int64 */
            scopeId?: number;
            status?: string;
            startedBy?: string;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            finishedAt?: string;
            cancelRequested?: boolean;
        };
        PageIndexRunSummary: {
            items?: components["schemas"]["IndexRunSummary"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        IndexRunView: {
            run?: components["schemas"]["IndexRunSummary"];
            error?: string;
            repositoriesByStatus?: {
                [key: string]: number;
            };
            repositories?: components["schemas"]["IndexRunRepoView"][];
            inProgress?: components["schemas"]["RepositoryRef"][];
        };
        CsrfToken: {
            headerName?: string;
            token?: string;
            parameterName?: string;
        };
        CsrfView: {
            headerName?: string;
            token?: string;
        };
        PageAppUser: {
            items?: components["schemas"]["AppUser"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
        DirectoryUserView: {
            username?: string;
            displayName?: string;
            email?: string;
            /** Format: int64 */
            appUserId?: number;
        };
        AuditEntry: {
            /** Format: int64 */
            id?: number;
            actor?: string;
            action?: string;
            target?: string;
            details?: string;
            /** Format: date-time */
            at?: string;
        };
        PageAuditEntry: {
            items?: components["schemas"]["AuditEntry"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            total?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    changeRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RoleChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppUser"];
                };
            };
        };
    };
    changeActive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ActiveChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppUser"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ValueChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Setting"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScmConnectionView"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScmConnectionUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScmConnectionView"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LdapConfigView"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LdapConfigUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LdapConfigView"];
                };
            };
        };
    };
    updateRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: "CALL" | "INSTANTIATION" | "METHOD_REF" | "TYPE_REF" | "EXTENDS" | "IMPLEMENTS" | "OVERRIDES" | "FIELD_READ" | "FIELD_WRITE" | "ANNOTATION";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RuleChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImpactRule"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnnotationChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntryPointAnnotation"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArtifactRepositoryView"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ArtifactRepositoryUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArtifactRepositoryView"];
                };
            };
        };
    };
    delete_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageIndexRunSummary"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StartRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["StartedRun"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    analyze: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImpactResult"];
                };
            };
        };
    };
    export: {
        parameters: {
            query: {
                format: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImpactRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Me"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PasswordChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Me"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                q?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAppUser"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Registration"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AppUser"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScmConnectionView"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ScmConnectionUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ScmConnectionView"];
                };
            };
        };
    };
    test: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    test_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LdapConfigUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    annotations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntryPointAnnotation"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnnotationChange"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["EntryPointAnnotation"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArtifactRepositoryView"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ArtifactRepositoryUpdate"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ArtifactRepositoryView"];
                };
            };
        };
    };
    test_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    index: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    uiConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UiConfig"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["SymbolDetail"];
                };
            };
        };
    };
    usages: {
        parameters: {
            query?: {
                confidence?: ("EXACT" | "RECOVERED" | "NAME_ONLY")[];
                kind?: ("CALL" | "INSTANTIATION" | "METHOD_REF" | "TYPE_REF" | "EXTENDS" | "IMPLEMENTS" | "OVERRIDES" | "FIELD_READ" | "FIELD_WRITE" | "ANNOTATION")[];
                repo?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageUsageView"];
                };
            };
        };
    };
    summary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsageSummary"];
                };
            };
        };
    };
    search: {
        parameters: {
            query: {
                q: string;
                kind?: "CLASS" | "INTERFACE" | "ENUM" | "RECORD" | "ANNOTATION_TYPE" | "METHOD" | "CONSTRUCTOR" | "FIELD";
                repo?: number;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageSymbolHit"];
                };
            };
        };
    };
    list_4: {
        parameters: {
            query?: {
                q?: string;
                status?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageRepositorySummary"];
                };
            };
        };
    };
    get_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepositoryDetail"];
                };
            };
        };
    };
    repositoryRuns: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageIndexRunRepoView"];
                };
            };
        };
    };
    graph: {
        parameters: {
            query?: {
                level?: string;
                focus?: string;
                includeExternal?: boolean;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepoGraph"];
                };
            };
        };
    };
    report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RepoGraphReport"];
                };
            };
        };
    };
    export_1: {
        parameters: {
            query?: {
                format?: string;
                level?: string;
                focus?: string;
                includeExternal?: boolean;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": Record<string, never>;
                };
            };
        };
    };
    get_5: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["IndexRunView"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Me"];
                };
            };
        };
    };
    csrf: {
        parameters: {
            query: {
                token: components["schemas"]["CsrfToken"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CsrfView"];
                };
            };
        };
    };
    list_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Setting"][];
                };
            };
        };
    };
    searchDirectory: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DirectoryUserView"][];
                };
            };
        };
    };
    rules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ImpactRule"][];
                };
            };
        };
    };
    list_6: {
        parameters: {
            query?: {
                actor?: string;
                action?: string;
                from?: string;
                to?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageAuditEntry"];
                };
            };
        };
    };
}
