-- Core schema for plan 2. Text columns are BYTE-sized; writers truncate with Utf8.truncateToBytes.

CREATE TABLE app_setting (
    setting_key   VARCHAR2(100 BYTE)  NOT NULL,
    setting_value VARCHAR2(4000 BYTE) NOT NULL,
    value_type    VARCHAR2(20 BYTE)   NOT NULL,
    description   VARCHAR2(500 BYTE)  NOT NULL,
    min_value     NUMBER(19),
    max_value     NUMBER(19),
    updated_by    VARCHAR2(200 BYTE),
    updated_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_app_setting PRIMARY KEY (setting_key),
    CONSTRAINT ck_app_setting_type CHECK (value_type IN ('INT', 'STRING', 'BOOL', 'CRON', 'LIST', 'DURATION'))
);

CREATE TABLE audit_log (
    id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    actor   VARCHAR2(200 BYTE)  NOT NULL,
    action  VARCHAR2(100 BYTE)  NOT NULL,
    target  VARCHAR2(500 BYTE)  NOT NULL,
    details VARCHAR2(4000 BYTE),
    at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (id)
);
CREATE INDEX ix_audit_log_at ON audit_log (at);

CREATE TABLE scm_connection (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    name             VARCHAR2(200 BYTE)  NOT NULL,
    type             VARCHAR2(30 BYTE)   NOT NULL,
    base_url         VARCHAR2(1000 BYTE) NOT NULL,
    username         VARCHAR2(200 BYTE),
    secret_enc       VARCHAR2(4000 BYTE),
    include_projects VARCHAR2(4000 BYTE),
    exclude_repos    VARCHAR2(4000 BYTE),
    enabled          NUMBER(1) DEFAULT 1 NOT NULL,
    last_test_status VARCHAR2(30 BYTE),
    last_test_at     TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_scm_connection PRIMARY KEY (id),
    CONSTRAINT uq_scm_connection_name UNIQUE (name),
    CONSTRAINT ck_scm_connection_type CHECK (type IN ('BITBUCKET_DC')),
    CONSTRAINT ck_scm_connection_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE scm_repository (
    id                  NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    connection_id       NUMBER(19)          NOT NULL,
    project_key         VARCHAR2(200 BYTE)  NOT NULL,
    slug                VARCHAR2(200 BYTE)  NOT NULL,
    clone_url           VARCHAR2(1000 BYTE) NOT NULL,
    default_branch      VARCHAR2(200 BYTE),
    last_indexed_commit VARCHAR2(64 BYTE),
    last_status         VARCHAR2(30 BYTE),
    last_indexed_at     TIMESTAMP WITH TIME ZONE,
    active              NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_scm_repository PRIMARY KEY (id),
    CONSTRAINT fk_scm_repository_connection FOREIGN KEY (connection_id) REFERENCES scm_connection (id),
    CONSTRAINT uq_scm_repository UNIQUE (connection_id, project_key, slug),
    CONSTRAINT ck_scm_repository_active CHECK (active IN (0, 1))
);

CREATE TABLE maven_module (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    repo_id        NUMBER(19)          NOT NULL,
    path           VARCHAR2(1000 BYTE) NOT NULL,
    group_id       VARCHAR2(300 BYTE),
    artifact_id    VARCHAR2(300 BYTE),
    version        VARCHAR2(100 BYTE),
    classpath_mode VARCHAR2(10 BYTE)   NOT NULL,
    CONSTRAINT pk_maven_module PRIMARY KEY (id),
    CONSTRAINT fk_maven_module_repo FOREIGN KEY (repo_id) REFERENCES scm_repository (id),
    CONSTRAINT uq_maven_module UNIQUE (repo_id, path),
    CONSTRAINT ck_maven_module_cp CHECK (classpath_mode IN ('FULL', 'PARTIAL', 'NONE'))
);

CREATE TABLE symbol (
    id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (CACHE 1000),
    symbol_key        VARCHAR2(4000 BYTE) NOT NULL,
    kind              VARCHAR2(20 BYTE)   NOT NULL,
    class_fqn         VARCHAR2(2000 BYTE) NOT NULL,
    member_name       VARCHAR2(1000 BYTE),
    display_signature VARCHAR2(4000 BYTE) NOT NULL,
    parent_id         NUMBER(19),
    origin            VARCHAR2(10 BYTE)   NOT NULL,
    name_only         NUMBER(1)           NOT NULL,
    artifact          VARCHAR2(500 BYTE),
    CONSTRAINT pk_symbol PRIMARY KEY (id),
    CONSTRAINT uq_symbol_key UNIQUE (symbol_key),
    CONSTRAINT fk_symbol_parent FOREIGN KEY (parent_id) REFERENCES symbol (id) ON DELETE SET NULL,
    CONSTRAINT ck_symbol_kind CHECK (kind IN ('CLASS', 'INTERFACE', 'ENUM', 'RECORD', 'ANNOTATION_TYPE',
                                              'METHOD', 'CONSTRUCTOR', 'FIELD')),
    CONSTRAINT ck_symbol_origin CHECK (origin IN ('SOURCE', 'BINARY')),
    CONSTRAINT ck_symbol_name_only CHECK (name_only IN (0, 1))
);
CREATE INDEX ix_symbol_class_member ON symbol (class_fqn, member_name);
CREATE INDEX ix_symbol_parent ON symbol (parent_id);

CREATE TABLE symbol_declaration (
    id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (CACHE 1000),
    symbol_id NUMBER(19)          NOT NULL,
    module_id NUMBER(19)          NOT NULL,
    file_path VARCHAR2(1000 BYTE) NOT NULL,
    line_no   NUMBER(10)          NOT NULL,
    CONSTRAINT pk_symbol_declaration PRIMARY KEY (id),
    CONSTRAINT fk_symbol_declaration_symbol FOREIGN KEY (symbol_id) REFERENCES symbol (id),
    CONSTRAINT fk_symbol_declaration_module FOREIGN KEY (module_id) REFERENCES maven_module (id)
);
CREATE INDEX ix_symbol_declaration_symbol ON symbol_declaration (symbol_id);
CREATE INDEX ix_symbol_declaration_module ON symbol_declaration (module_id);

CREATE TABLE usage (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY (CACHE 1000),
    from_symbol_id NUMBER(19)          NOT NULL,
    to_symbol_id   NUMBER(19)          NOT NULL,
    module_id      NUMBER(19)          NOT NULL,
    kind           VARCHAR2(20 BYTE)   NOT NULL,
    confidence     VARCHAR2(10 BYTE)   NOT NULL,
    file_path      VARCHAR2(1000 BYTE) NOT NULL,
    line_no        NUMBER(10)          NOT NULL,
    column_no      NUMBER(10)          NOT NULL,
    snippet        VARCHAR2(4000 BYTE),
    CONSTRAINT pk_usage PRIMARY KEY (id),
    CONSTRAINT fk_usage_from FOREIGN KEY (from_symbol_id) REFERENCES symbol (id),
    CONSTRAINT fk_usage_to FOREIGN KEY (to_symbol_id) REFERENCES symbol (id),
    CONSTRAINT fk_usage_module FOREIGN KEY (module_id) REFERENCES maven_module (id),
    CONSTRAINT ck_usage_kind CHECK (kind IN ('CALL', 'INSTANTIATION', 'METHOD_REF', 'TYPE_REF', 'EXTENDS',
                                             'IMPLEMENTS', 'OVERRIDES', 'FIELD_READ', 'FIELD_WRITE', 'ANNOTATION')),
    CONSTRAINT ck_usage_confidence CHECK (confidence IN ('EXACT', 'RECOVERED', 'NAME_ONLY'))
);
CREATE INDEX ix_usage_to ON usage (to_symbol_id);
CREATE INDEX ix_usage_from ON usage (from_symbol_id);
CREATE INDEX ix_usage_module ON usage (module_id);
