-- Plan 3: case-insensitive symbol search, index-only impact BFS, entry-point and propagation rules.

-- Upper-cased simple class name and member name. SUBSTRB + CAST bound the width: UPPER/SUBSTR alone widen to 4000.
ALTER TABLE symbol ADD (
    search_class  VARCHAR2(500 BYTE) GENERATED ALWAYS AS (CAST(SUBSTRB(UPPER(SUBSTR(class_fqn,
                      GREATEST(INSTR(class_fqn, '.', -1), INSTR(class_fqn, '$', -1)) + 1)), 1, 500)
                      AS VARCHAR2(500 BYTE))) VIRTUAL,
    search_member VARCHAR2(500 BYTE) GENERATED ALWAYS AS (CAST(SUBSTRB(UPPER(member_name), 1, 500)
                      AS VARCHAR2(500 BYTE))) VIRTUAL
);
CREATE INDEX ix_symbol_search ON symbol (search_class, search_member);
CREATE INDEX ix_symbol_search_member ON symbol (search_member);

-- Impact BFS filters usage by target, kind and confidence and reads from/module/id: a covering index, so the BFS
-- never visits the table (file, line and snippet are read afterwards for the kept edges only). It also backs fk_usage_to.
CREATE INDEX ix_usage_bfs ON usage (to_symbol_id, kind, confidence, from_symbol_id, module_id, id);
DROP INDEX ix_usage_to;

CREATE TABLE entry_point_annotation (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    annotation_fqn VARCHAR2(500 BYTE) NOT NULL,
    label          VARCHAR2(200 BYTE) NOT NULL,
    enabled        NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_entry_point_annotation PRIMARY KEY (id),
    CONSTRAINT uq_entry_point_annotation UNIQUE (annotation_fqn),
    CONSTRAINT ck_entry_point_enabled CHECK (enabled IN (0, 1))
);
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.web.bind.annotation.RequestMapping', 'HTTP');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.web.bind.annotation.GetMapping', 'HTTP');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.web.bind.annotation.PostMapping', 'HTTP');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.web.bind.annotation.PutMapping', 'HTTP');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.web.bind.annotation.DeleteMapping', 'HTTP');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.web.bind.annotation.PatchMapping', 'HTTP');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.scheduling.annotation.Scheduled', 'Zamanlanmış görev');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.kafka.annotation.KafkaListener', 'Kafka dinleyici');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.jms.annotation.JmsListener', 'JMS dinleyici');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.amqp.rabbit.annotation.RabbitListener', 'RabbitMQ dinleyici');
INSERT INTO entry_point_annotation (annotation_fqn, label) VALUES ('org.springframework.context.event.EventListener', 'Uygulama olayı');

CREATE TABLE impact_relation_rule (
    usage_kind      VARCHAR2(20 BYTE) NOT NULL,
    propagates      NUMBER(1)         NOT NULL,
    shown_at_level1 NUMBER(1)         NOT NULL,
    CONSTRAINT pk_impact_relation_rule PRIMARY KEY (usage_kind),
    CONSTRAINT ck_impact_rule_kind CHECK (usage_kind IN ('CALL', 'INSTANTIATION', 'METHOD_REF', 'TYPE_REF', 'EXTENDS',
                                                         'IMPLEMENTS', 'OVERRIDES', 'FIELD_READ', 'FIELD_WRITE',
                                                         'ANNOTATION')),
    CONSTRAINT ck_impact_rule_flags CHECK (propagates IN (0, 1) AND shown_at_level1 IN (0, 1))
);
INSERT INTO impact_relation_rule VALUES ('CALL', 1, 1);
INSERT INTO impact_relation_rule VALUES ('INSTANTIATION', 1, 1);
INSERT INTO impact_relation_rule VALUES ('METHOD_REF', 1, 1);
INSERT INTO impact_relation_rule VALUES ('OVERRIDES', 1, 1);
INSERT INTO impact_relation_rule VALUES ('EXTENDS', 1, 1);
INSERT INTO impact_relation_rule VALUES ('IMPLEMENTS', 1, 1);
INSERT INTO impact_relation_rule VALUES ('TYPE_REF', 0, 1);
INSERT INTO impact_relation_rule VALUES ('ANNOTATION', 0, 1);
INSERT INTO impact_relation_rule VALUES ('FIELD_READ', 0, 1);
INSERT INTO impact_relation_rule VALUES ('FIELD_WRITE', 0, 1);
