-- Plan 4: Maven repositories, declared dependencies, index run history and acquisition settings.

CREATE TABLE artifact_repository (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR2(200 BYTE)  NOT NULL,
    url        VARCHAR2(1000 BYTE) NOT NULL,
    username   VARCHAR2(200 BYTE),
    secret_enc VARCHAR2(4000 BYTE),
    mirror_of  VARCHAR2(200 BYTE),
    sort_order NUMBER(10) DEFAULT 0 NOT NULL,
    enabled    NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_artifact_repository PRIMARY KEY (id),
    CONSTRAINT uq_artifact_repository_name UNIQUE (name),
    CONSTRAINT ck_artifact_repository_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE module_dependency (
    id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    module_id   NUMBER(19)         NOT NULL,
    group_id    VARCHAR2(300 BYTE) NOT NULL,
    artifact_id VARCHAR2(300 BYTE) NOT NULL,
    version     VARCHAR2(100 BYTE),
    scope       VARCHAR2(20 BYTE)  NOT NULL,
    CONSTRAINT pk_module_dependency PRIMARY KEY (id),
    CONSTRAINT fk_module_dependency_module FOREIGN KEY (module_id) REFERENCES maven_module (id)
);
CREATE INDEX ix_module_dependency_module ON module_dependency (module_id);
CREATE INDEX ix_module_dependency_artifact ON module_dependency (group_id, artifact_id);

CREATE TABLE index_run (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    trigger_type VARCHAR2(20 BYTE)  NOT NULL,
    scope        VARCHAR2(20 BYTE)  NOT NULL,
    scope_id     NUMBER(19),
    status       VARCHAR2(20 BYTE)  NOT NULL,
    started_by   VARCHAR2(200 BYTE) NOT NULL,
    started_at   TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_index_run PRIMARY KEY (id),
    CONSTRAINT ck_index_run_trigger CHECK (trigger_type IN ('SCHEDULED', 'MANUAL')),
    CONSTRAINT ck_index_run_scope CHECK (scope IN ('ALL', 'CONNECTION', 'REPOSITORY')),
    CONSTRAINT ck_index_run_status CHECK (status IN ('RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', 'INTERRUPTED'))
);
CREATE INDEX ix_index_run_started ON index_run (started_at);

CREATE TABLE index_run_repo (
    id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    run_id         NUMBER(19)          NOT NULL,
    repo_id        NUMBER(19)          NOT NULL,
    commit_sha     VARCHAR2(64 BYTE),
    status         VARCHAR2(20 BYTE)   NOT NULL,
    classpath_mode VARCHAR2(10 BYTE),
    error          VARCHAR2(4000 BYTE),
    symbol_count   NUMBER(10) DEFAULT 0 NOT NULL,
    usage_count    NUMBER(10) DEFAULT 0 NOT NULL,
    warning_count  NUMBER(10) DEFAULT 0 NOT NULL,
    duration_ms    NUMBER(19) DEFAULT 0 NOT NULL,
    finished_at    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_index_run_repo PRIMARY KEY (id),
    CONSTRAINT fk_index_run_repo_run FOREIGN KEY (run_id) REFERENCES index_run (id),
    CONSTRAINT fk_index_run_repo_repo FOREIGN KEY (repo_id) REFERENCES scm_repository (id),
    CONSTRAINT ck_index_run_repo_status CHECK (status IN ('SUCCESS', 'SUCCESS_PARTIAL', 'FAILED', 'CLONE_FAILED',
                                                          'SKIPPED_UNCHANGED', 'SKIPPED_NOT_JAVA', 'INTERRUPTED')),
    CONSTRAINT ck_index_run_repo_cp CHECK (classpath_mode IS NULL OR classpath_mode IN ('FULL', 'PARTIAL', 'NONE'))
);
CREATE INDEX ix_index_run_repo_run ON index_run_repo (run_id);
CREATE INDEX ix_index_run_repo_repo ON index_run_repo (repo_id, finished_at);

INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('index.maven_executable', 'mvn', 'STRING', 'Maven komutu (PATH üzerinde ya da tam yol)', NULL, NULL);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('index.maven_local_repository', '/data/impact-analyzer/m2', 'STRING', 'Maven yerel depo dizini (maven.repo.local)', NULL, NULL);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('index.git_depth', '1', 'INT', 'Git klon/fetch derinliği (commit sayısı)', 1, 1000);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('index.git_timeout', 'PT5M', 'DURATION', 'Git ağ işlemi zaman aşımı', NULL, NULL);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('index.source_roots', 'src/main/java,src/test/java', 'LIST', 'Modül başına indekslenen kaynak dizinleri (modüle göre)', NULL, NULL);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('scm.connect_timeout', 'PT10S', 'DURATION', 'SCM API bağlantı zaman aşımı', NULL, NULL);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('scm.read_timeout', 'PT60S', 'DURATION', 'SCM API okuma zaman aşımı', NULL, NULL);
