-- Plan 6: users and roles (spec §7.2), local accounts, the single LDAP configuration row and authentication settings.

CREATE TABLE app_user (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    username        VARCHAR2(200 BYTE) NOT NULL,
    source          VARCHAR2(10 BYTE)  NOT NULL,
    display_name    VARCHAR2(200 BYTE),
    email           VARCHAR2(320 BYTE),
    role            VARCHAR2(10 BYTE)  NOT NULL,
    role_granted_by VARCHAR2(200 BYTE),
    role_granted_at TIMESTAMP WITH TIME ZONE,
    last_login_at   TIMESTAMP WITH TIME ZONE,
    active          NUMBER(1) DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_username UNIQUE (username),
    CONSTRAINT ck_app_user_source CHECK (source IN ('LOCAL', 'LDAP')),
    CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'USER')),
    CONSTRAINT ck_app_user_active CHECK (active IN (0, 1)),
    CONSTRAINT ck_app_user_lower CHECK (username = LOWER(username))
);
CREATE INDEX ix_app_user_role ON app_user (role, active);

CREATE TABLE local_account (
    username             VARCHAR2(200 BYTE) NOT NULL,
    password_hash        VARCHAR2(100 BYTE) NOT NULL,
    must_change_password NUMBER(1) DEFAULT 1 NOT NULL,
    enabled              NUMBER(1) DEFAULT 1 NOT NULL,
    failed_attempts      NUMBER(5) DEFAULT 0 NOT NULL,
    locked_until         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_local_account PRIMARY KEY (username),
    CONSTRAINT fk_local_account_user FOREIGN KEY (username) REFERENCES app_user (username),
    CONSTRAINT ck_local_account_change CHECK (must_change_password IN (0, 1)),
    CONSTRAINT ck_local_account_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE ldap_config (
    id                 NUMBER(1) DEFAULT 1 NOT NULL,
    enabled            NUMBER(1) DEFAULT 0 NOT NULL,
    url                VARCHAR2(1000 BYTE),
    base_dn            VARCHAR2(1000 BYTE),
    user_search_base   VARCHAR2(1000 BYTE),
    user_search_filter VARCHAR2(1000 BYTE) DEFAULT '(uid={0})' NOT NULL,
    user_query_filter  VARCHAR2(1000 BYTE) DEFAULT '(|(uid={0}*)(cn={0}*)(mail={0}*))' NOT NULL,
    username_attr      VARCHAR2(100 BYTE)  DEFAULT 'uid' NOT NULL,
    display_name_attr  VARCHAR2(100 BYTE)  DEFAULT 'cn' NOT NULL,
    email_attr         VARCHAR2(100 BYTE)  DEFAULT 'mail' NOT NULL,
    bind_dn            VARCHAR2(1000 BYTE),
    bind_password_enc  VARCHAR2(4000 BYTE),
    updated_by         VARCHAR2(200 BYTE),
    updated_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_ldap_config PRIMARY KEY (id),
    CONSTRAINT ck_ldap_config_single CHECK (id = 1),
    CONSTRAINT ck_ldap_config_enabled CHECK (enabled IN (0, 1))
);
INSERT INTO ldap_config (id) VALUES (1);

INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('auth.password_min_length', '12', 'INT', 'Yerel hesap şifresinin en az uzunluğu', 8, 128);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('auth.ldap_connect_timeout', 'PT5S', 'DURATION', 'LDAP bağlantı zaman aşımı', NULL, NULL);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('auth.ldap_read_timeout', 'PT10S', 'DURATION', 'LDAP okuma/arama zaman aşımı', NULL, NULL);
INSERT INTO app_setting (setting_key, setting_value, value_type, description, min_value, max_value) VALUES
    ('auth.ldap_search_max_results', '50', 'INT', 'Dizin kullanıcı aramasında dönen en fazla kayıt', 1, 1000);
